### ISSUE TITLE
Blend-subtitles does not work as expected

### ISSUE THREAD

**Issue by ParadoxSpiral** [haasn/mpvhq#5] opened 2015-04-05 18:35 UTC
When playing the below linked file at 00:14:43 a sheet of paper is translated.
If I understand it correctly, the colour with which the original text is covered, should have the colour of the paper with blend-subtitles enabled. This is not the case, it is slightly tinted, a rectangle can be seen. The translated text at the bottom of the paper seems to not have this issue.
If it is relevant: the file is 10bit.
All screenshots are taken with: --start=00:14:43 --pause

Source (with --no-config and --vo=opengl and --no-sub):
https://a.pomf.se/hihapv.png

Screenshot with --no-config and --vo=opengl:
https://a.pomf.se/mioxtj.png

Screenshot with my personal config (includes blend-subtitles):
https://a.pomf.se/hjradu.png
Config: https://a.pomf.se/ektlyn.conf

File:
The file is 2GB big, and will therefore take forever for me to upload (estimated ~10h).
I'll update this when the file is up.

Subs:
https://a.pomf.se/rklihm.mks

mpvhq-version:

``` bash
$ mpv --version
mpv git-9311b1e (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-04-05T13:09:40
ffmpeg library versions:
   libavutil       54.22.100
   libavcodec      56.34.100
   libavformat     56.29.100
   libswscale      3.1.101
   libavfilter     5.13.101
   libswresample   1.1.100
```

Maybe the subber made a mistake, but I don't know how to check that?

**Comment by ParadoxSpiral** [comment] 2015-04-05 20:00
/g/ suggests that this is due to shitty typesetting.
But I'll leave that decision to you.

https://boards.4chan.org/g/thread/47352550/mpv-mpv-general#p47371058

"
I'm going to go with shitty typesetting
The offending line:
http://pastebin.com/raw.php?i=cv8aL91f (4chan's spam detection is seriously fucking annoying)
They use the color "E4E1E2" (that's in BGR format, so E2E1E4 is normal RGB hex), but from what I can tell, the average color in that area is closer to E7E7E9, so they might have either picked the color with a fucked up color space or just not averaged out the color in multiple areas of the image.
"

**Comment by haasn** [comment] 2015-04-06 00:29
If it happens with `--no-config --vo=opengl`, then it is absolutely a bug in the typesetting. If they match at all, then that config would make them match.

(The default setting for target-trc, auto, means that there's no gamma correction for either the video or the subtitles, since auto means the output TRC is always assumed to be equal to the input TRC)

What you can try doing is using `--vf=format=colormatrix=bt.601` or `--vf=format=colormatrix=bt.709``to see if that maybe fixes it. You can also try playing around with``--ass-vsfilter-color-compat```.

> The file is 2GB big, and will therefore take forever for me to upload (estimated ~10h).

You can cut out a portion of the file using various tools (google should help).

Closing because it's not a bug on our side.

**Closed as completed** 2015-04-06 00:33 UTC
